import {DATA,CARDS,SAVE_KEY,DEFAULTS,FACES,newGame,act,current,unlocked,available,basePower,crewPower,supplyCost,finalOptions,controls} from './engine-v08.mjs';
const root=document.querySelector('#voyage'),dlg=document.querySelector('#voyageDialog'),body=document.querySelector('#voyageBody');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const colors=['#df4a3f','#4598ef','#46b879','#e9c65b'];let state=null,zoom=false,aiTimer=null,dialogView=null;
const positions={1:[[47.8,59.7,7.4,10.3],[56.3,59.7,7.4,10.3],[64.7,59.7,7.4,10.3]],2:[[42.5,39.2,7.2,10.3],[51.2,39.2,7.2,10.3],[59.8,39.2,7.2,10.3]],3:[[48.1,17.5,7.5,10.4],[58.2,17.5,7.5,10.4]],4:[[83,14.4,9.3,15.5]]};
const locations=[['tavern','Tavern',2.8,63.9],['market','Market',11.6,63.9],['dock','Dock',20.4,63.9],['work','Harbor Work',29.2,63.9],['quarters','Crew Quarters',2.8,73.7],['black','Black Market',11.6,73.7],['veteran',"Veteran’s Den",20.4,73.7],['witch','Sea Witch',29.2,73.7]];
function image(c){const a=c.art;return `<div class="art" role="img" aria-label="${esc(c.name)}" style="aspect-ratio:${a.width}/${a.height};background-image:url('assets/v08-${a.sheet}.png');background-size:${a.sourceWidth/a.width*100}% ${a.sourceHeight/a.height*100}%;background-position:${a.x/(a.sourceWidth-a.width)*100}% ${a.y/(a.sourceHeight-a.height)*100}%"></div>`}
function lines(t){return t.split('\n').filter(x=>x.trim()).map(x=>`<p>${esc(x)}</p>`).join('')}
function details(c){if(c.kind==='crew')return `<div class="vStats"><span>${c.tier}</span><span>${c.cost} Gold</span><span>Power ${c.power}</span></div>${lines(c.text)}`;
 if(c.kind==='treasure')return lines(c.text)+'<p><b>Active Treasure:</b> +1 Power in Zone III / Final only. Maximum 3 active.</p>';
 if(c.kind==='final')return `<b>STEP 1 · Optional Final Edge +1</b>${lines(c.step1)}<b>STEP 2</b>${lines(c.step2)}<p><b>Failure:</b> lose 1 Crew unless prevented; discard this Final; reveal next. All 5 failed = everyone loses.</p>`;
 return `<div class="vStats"><span>Target ${c.target}</span></div><b>REWARDS</b>${lines(c.text)}`}
function card(id,button=''){const c=CARDS[id];return `<article class="vCard"><h3>${esc(c.name)}</h3>${image(c)}<div class="text">${details(c)}${button}</div></article>`}
function modal(title,html,locked=false){document.querySelector('#voyageTitle').textContent=title;body.onchange=null;body.innerHTML=html;document.querySelector('#voyageClose').hidden=locked;dlg.dataset.locked=String(locked);if(!dlg.open)dlg.showModal();dlg.scrollTop=0}
function close(){if(dlg.dataset.locked==='true')return;dlg.close();dialogView=null}
document.querySelector('#voyageClose').onclick=close;dlg.addEventListener('cancel',e=>{if(dlg.dataset.locked==='true')e.preventDefault()});
function save(){if(state){localStorage.setItem(SAVE_KEY,JSON.stringify(state));window.dispatchEvent(new Event('captainsdash:saved'))}}
function toast(t){const el=document.querySelector('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function doAct(a){try{state=act(state,a);save();render();if(state.status!=='playing'){dlg.close();return true}else if(state.exp)showExp();else if(state.pending)recruit(false);else{dlg.close();dialogView=null}scheduleAI();return true}catch(err){const el=document.querySelector('#vError');if(el){el.textContent=err.message;el.hidden=false}else toast(err.message);return false}}
function playersBar(){return state.players.map((p,i)=>`<span style="color:${colors[i]}">${i===state.turn?'▶ ':''}${esc(p.name)} · ${p.gold}G / ${p.supply}S</span>`).join(' &nbsp; | &nbsp; ')}
function render(){const p=current(state);root.hidden=false;document.querySelector("#app").hidden=true;if(state.status!=='playing'){root.innerHTML=`<div class="vWin"><div style="font-size:80px">${state.status==='won'?'♛':'☠'}</div><h2>${state.status==='won'?esc(state.players[state.winner].name)+' wins!':'The Final Isle is lost'}</h2><p>${state.status==='won'?'The final mission is complete. Your legend begins.':'All five Final Missions failed. All captains lose this voyage.'}</p><button data-v="menu">Main Menu</button><button data-v="history">Voyage history</button></div>`;dlg.close();return}
 let slots='';for(const z of [1,2,3,4]){const stacks=z===4?[state.final]:state.stacks[z];stacks.forEach((st,i)=>{const [x,y,w,h]=positions[z][i];slots+=`<button class="vSlot ${unlocked(state,z)?'':'locked'}" style="left:${x}%;top:${y}%;width:${w}%;height:${h}%" data-mission="${st[0]||''}" ${!st.length?'disabled':''} aria-label="${st.length?esc(CARDS[st[0]].name):'Mission complete'}">${st.length?image(CARDS[st[0]]):''}<span class="slotInfo">${!unlocked(state,z)?'LOCKED':st.length?`TARGET ${CARDS[st[0]].target} · ${st.length} left`:'COMPLETE'}</span></button>`})}
 let token={x:18,y:88};if(state.exp){const c=CARDS[state.exp.mission],z=c.zone||4,idx=z===4?0:Math.max(0,state.stacks[z].findIndex(st=>st.includes(c.id)));token={x:positions[z][idx][0]-4,y:positions[z][idx][1]+3}}
 root.innerHTML=`<header class="vHud"><h1>Captain’s Dash</h1><div class="resources" style="color:${colors[state.turn]}">Round ${state.round} · ${esc(p.name)} · ${p.gold} Gold · ${p.supply} Supply</div><button data-v="crew">Crew & Treasure</button><button data-v="menu">Menu</button></header><div class="vProgress"><span>Zone II: ${Math.min(2,state.progress[0])}/2</span><span>Zone III: ${Math.min(3,state.progress[1])}/3</span><span>Final: ${Math.min(1,state.progress[2])}/1</span><span>Final Missions: ${state.final.length}/5</span></div><div class="vBoardScroll"><div class="vBoard ${zoom?'zoomed':''}"><img src="assets/v08-board.png" alt="Captain’s Dash v0.8 archipelago board">${slots}${locations.map(([id,name,x,y])=>`<button class="vAction" style="left:${x}%;top:${y}%;width:8.2%;height:9.4%" data-v="${id}" aria-label="${name}" title="${name}">${name}</button>`).join('')}<div class="token" style="--player:${colors[state.turn]};left:${token.x}%;top:${token.y}%"></div><div class="remaining" aria-label="${state.final.length} Final Missions remain">${Array.from({length:5},(_,i)=>`<span class="${i<state.final.length?'':'used'}"></span>`).join('')}</div><button class="vAction" data-v="tavern" aria-label="Crew Market" style="left:71%;top:77%;width:25%;height:7%">Crew Market</button><button class="vAction" data-v="history" aria-label="Mission Discard" style="left:72%;top:87%;width:9%;height:9%">Mission Discard</button></div></div><div class="vFoot"><button data-v="dock">⚓ Expedition</button><button data-v="zoom">${zoom?'Fit board':'Zoom board'}</button><button data-v="cards">All 84 cards</button><button data-v="history">History</button><button data-v="rules">Rules</button><p>${playersBar()}</p>${state.exp?'<button data-v="resume">Resume Expedition</button>':state.pending?'<button data-v="black">Finish Black Market</button>':''}</div>`;
}
function busy(){return state.exp||state.pending||(state.mode==='ai'&&state.turn===1)}
function recruit(vet){dialogView=vet?'veteran':'tavern';const ids=vet?state.veteranMarket:state.market,p=current(state);modal(vet?'Veteran’s Den':state.pending?'Black Market · discounted recruit':'Tavern · recruit one Crew',`<p>Recruit 1 Crew. ${state.pending?'Refresh already used your main action. Recruit with 1 Gold discount or finish.':''}</p><div id="vError" hidden class="vError"></div><div class="vGrid">${ids.map(id=>{const price=Math.max(0,CARDS[id].cost-(state.pending?1:0)-p.discount);return card(id,`<button data-recruit="${id}" data-pool="${vet?'veteran':'common'}" ${p.gold<price?'disabled':''}>Recruit · ${price} Gold</button>`)}).join('')}</div>${state.pending?'<button data-black-skip>Finish without recruiting</button>':''}`,!!state.pending)}
function showCrew(){const p=current(state);modal('Your Crew & Treasure',`<p>${p.crew.length} owned Crew · select up to 4 ready Crew per expedition. ${p.treasures.length} Treasures · activate up to 3 when sailing.</p><div class="vGrid">${p.crew.map(c=>card(c.id,`<p><b>${c.exhausted?'EXHAUSTED':'READY'}</b></p>`)).join('')}${p.treasures.map(id=>card(id)).join('')}</div>`)}
function showDock(){modal('Choose an Expedition',`<p>Choose any face-up Mission in an unlocked Zone. Supply costs: 1 / 3 / 6 / 9. No route or Sailing requirement.</p><div class="vGrid">${[1,2,3].flatMap(z=>state.stacks[z].filter(st=>st.length).map(st=>card(st[0],`<button data-mission="${st[0]}" ${unlocked(state,z)?'':'disabled'}>${unlocked(state,z)?'Prepare Expedition':'Zone locked'}</button>`))).join('')}${state.final.length?card(state.final[0],`<button data-mission="${state.final[0]}" ${unlocked(state,4)?'':'disabled'}>Prepare Final Expedition</button>`):''}</div>`)}
function prep(id){if(state.exp)return showExp();if(state.pending)return recruit(false);if(state.mode==='ai'&&state.turn===1)return;const c=CARDS[id];if(!available(state,id)){toast('This Zone is not yet unlocked.');return}const p=current(state);dialogView='prepare';
 modal(c.kind==='final'?'Prepare the Final Expedition':'Prepare Expedition',`<div class="vSplit">${card(id)}<div class="vForm"><p>Choose up to 4 ready Crew and 3 active Treasures.</p><div id="vError" hidden class="vError"></div><h3>Crew</h3><div class="vSelect">${p.crew.map((x,i)=>`<label><input type="checkbox" name="sCrew" value="${x.uid}" ${x.exhausted?'disabled':i<4?'checked':''}><span>${esc(CARDS[x.id].name)} · Power ${CARDS[x.id].power}<small>${x.exhausted?'Exhausted':CARDS[x.id].tier}</small></span></label>`).join('')}</div><h3>Active Treasure</h3><div class="vSelect">${p.treasures.map((id,i)=>`<label><input type="checkbox" name="sTreasure" value="${id}" ${i<3?'checked':''}><span>${esc(CARDS[id].name)}</span></label>`).join('')||'<p>No Treasure yet.</p>'}</div>${c.kind==='final'?`<h3>Step 1 · Favored Approach</h3><select id="approach"><option value="skip">Attempt without Final Edge</option><option value="check">Check my build for Final Edge +1</option>${id==='F2'?'<option value="sacrifice">Discard 1 selected Crew (+1 Edge)</option>':id==='F3'?'<option value="supply">Pay 3 extra Supply (+1 Edge)</option><option value="exhaust">Exhaust 1 selected Veteran (+1 Edge)</option>':id==='F4'?'<option value="gold">Pay 6 Gold (+1 Edge)</option><option value="treasure">Discard 1 active Treasure (+1 Edge)</option>':id==='F8'?'<option value="safe">Pay 3 Gold + 2 Supply (+1 Edge)</option>':''}</select><select id="sacrifice" aria-label="Card for sacrifice"><option value="">Choose card if required</option>${p.crew.map(x=>`<option value="${x.uid}">${esc(CARDS[x.id].name)} (${x.uid})</option>`).join('')}${p.treasures.map(id=>`<option value="${id}">${esc(CARDS[id].name)}</option>`).join('')}</select><p style="font-size:14px">Build checks use selected Crew/active Treasure; Elite counts as Veteran. Exhausting a Veteran removes its Power for this expedition.</p>`:''}${p.treasures.includes('T07')?'<label><input type="checkbox" id="powder"> Black Powder Horn: pay 1 extra Supply, gain 2 Gold</label>':''}<div class="vSummary" id="previewCost"></div><div class="vToolbar"><button data-launch="${id}">Confirm Expedition & Pay</button>${p.crew.some(x=>x.id==='C13'&&!x.exhausted)||p.treasures.includes('T01')||p.blessing==='sight'?`<button data-peek="${id}">Inspect lower Mission</button>`:''}</div></div></div>`);
 const summary=()=>{const crew=[...body.querySelectorAll('[name=sCrew]:checked')].map(x=>x.value),treasures=[...body.querySelectorAll('[name=sTreasure]:checked')].map(x=>x.value);const e={mission:id,crew,treasures,edge:0,blessing:p.blessing},z=c.zone||4,opt=body.querySelector('#approach')?.value;let cost=supplyCost(p,z,treasures)+(body.querySelector('#powder')?.checked?1:0)+(opt==='supply'?3:opt==='safe'?2:0);body.querySelector('#previewCost').textContent=`${crew.length}/4 Crew · ${treasures.length}/3 Treasures · Base Power ${basePower(p,e)} before Step 1 · Pay ${cost} Supply${opt==='gold'?' + 6 Gold':opt==='safe'?' + 3 Gold':''} · Roll ${z===4?3:z} dice.`};body.onchange=summary;summary();
}
function showExp(){if(!state.exp)return;const e=state.exp,p=current(state),c=CARDS[e.mission];dialogView='exp';let html=`<p>${esc(c.name)} · Supply paid: ${e.paid} · Final Edge: +${e.edge}</p><div id="vError" class="vError" hidden></div>`;
 if(e.phase==='ready')html+=`<div class="vTotal">Crew Power ${crewPower(p,e)} · Total before dice ${basePower(p,e)}</div><p>Your selection and paid cost are saved. Close and continue later without paying again.</p><button data-e="roll">Roll ${c.zone||3} Mission Dice</button>`;
 if(['dice','loss','result','treasure'].includes(e.phase))html+=`<div class="dice">${e.dice.map((d,i)=>`<div class="die ${d==='SKULL'?'skull':''}">${d==='SKULL'?'☠':d==='GOLD'?'G':d}</div>`).join('')}</div>`;
 if(e.phase==='dice')html+=`<div class="vTotal">Power ${basePower(p,e)+e.dice.reduce((n,d)=>n+(typeof d==='number'?d:0),0)+(e.bonus||0)} / Target ${c.target}</div><p>Use at most one Dice Control. Skull can never be changed.</p><div class="vToolbar">${controls(state).map(id=>id==='fortune'?e.dice.map((_,i)=>`<button data-control="fortune" data-index="${i}">Fortune · reroll die ${i+1}</button>`).join(''):`<button data-control="${id}">${esc(CARDS[id].name)}</button>`).join('')}</div><button data-e="resolve">Resolve Mission</button>`;
 if(e.phase==='loss'){const participants=p.crew.filter(x=>e.crew.includes(x.uid)),berserker=participants.find(x=>x.id==='C11');html+=`<div class="vNotice">Mission failed${e.dice.includes('SKULL')?' — Skull is final':''}. Lose 1 participating Crew or use protection.</div><div class="vToolbar">${participants.some(x=>x.id==='C12'&&!x.exhausted)?'<button data-protect="surgeon">Exhaust Surgeon · save Crew</button>':''}${e.treasures.includes('T19')?'<button data-protect="medallion">Discard Medallion · save Crew</button>':''}${participants.filter(x=>!berserker||x.uid===berserker.uid).map(x=>`<button data-loss="${x.uid}">Lose ${esc(CARDS[x.id].name)}</button>`).join('')}</div>`}
 if(e.phase==='treasure')html+=`<h3>Choose your Treasure</h3><div class="vGrid">${e.choices.map(id=>card(id,`<button data-keep="${id}">Keep this Treasure</button>`)).join('')}</div>`;
 if(e.phase==='result')html+=`<div class="vTotal">${e.success?'SUCCESS':'MISSION FAILED'} · ${e.total} / ${c.target}</div><p>Rewards, refunds and losses have been applied. ${p.gold} Gold · ${p.supply} Supply.</p><button data-e="finish">End Turn</button>`;
 modal('Expedition',html,e.phase==='loss'||e.phase==='treasure'||e.phase==='result');
}
function action(name){if(name==='menu'){save();clearTimeout(aiTimer);dlg.close();root.hidden=true;document.querySelector("#app").hidden=false;document.querySelector('#transition').classList.remove('show');return}if(name==='resume')return showExp();if(name==='zoom'){zoom=!zoom;render();return}
 if(name==='crew')return showCrew();if(name==='history')return modal('Voyage history',`<div class="vLog">${state.log.map(l=>`<p>${esc(l)}</p>`).join('')}</div><h3>Mission Discard</h3><div class="vGrid">${state.missionDiscard.map(x=>card(x.id,`<p>${esc(x.player)} · ${x.result}</p>`)).join('')}</div>`);
 if(name==='cards')return modal('All 84 cards',`<div class="vToolbar">${['crew','treasure','zone1','zone2','zone3','final'].map(k=>`<button data-category="${k}">${k.toUpperCase()}</button>`).join('')}</div><div id="collection" class="vGrid">${DATA.cards.filter(c=>c.kind==='crew').map(c=>card(c.id)).join('')}</div>`);
 if(name==='rules')return modal('Rules v0.8',`<p>One main action per turn. Use Pirate Haven to prepare, then choose any available Mission in an unlocked Zone. Select up to 4 ready Crew and 3 active Treasures. Pay Supply before rolling.</p><p>Dice: SKULL / 0 / 0 / 1 / 2 / GOLD. Any Skull immediately fails; Gold still pays. Otherwise total Power must meet Target. Only one Dice Control per roll.</p><p>Normal failure: lose 1 participating Crew unless prevented; Mission stays. Success: rewards, discard, reveal lower card. Empty stacks never refill.</p><p>Final: optional Step 1 for +1 Edge, then 3 dice / Target 16. Success wins. Failure discards the active Final permanently. Five failures = shared loss.</p><h3>Prototype defaults</h3><p>These operational defaults resolve open points for this build and remain subject to playtesting:</p><ul><li>No Haven occupancy blocking; one main action per turn.</li><li>Four copies of each Crew type in its pool. Common Crew in Tavern; Veteran + Elite in dedicated pool.</li><li>Final checks use participating Crew / active Treasure; Elite counts as Veteran. Step 1 exhaustion removes Power.</li><li>Sea Witch costs 2 Gold for the next expedition.</li><li>Atlas high targets: 4 / 6 / 10 for Zones I / II / III.</li><li>Unchosen Treasure goes to discard. Empty Treasure deck reshuffles discard.</li><li>Veteran Pirate readies the first exhausted Crew after success.</li></ul><p>Base setup: 3 Gold, 4 Supply, 2 Deckhands. P2 +1 Gold; P3/P4 +1 Gold +1 Supply. Old-version saved games are preserved separately and cannot be resumed under these changed rules.</p>`);
 if(busy()){if(state.status!=='playing'){dlg.close();return true}else if(state.exp)showExp();else if(state.pending)recruit(false);return}
 if(name==='tavern'||name==='veteran')return recruit(name==='veteran');if(name==='dock')return showDock();if(name==='work')return modal('Harbor Work','<p>Gain 2 Gold and end your turn.</p><button data-work>Gain 2 Gold</button>');
 if(name==='market')return modal('Market',`<div class="vForm"><p>Buy up to 5 Supply. 1 Gold = 1 Supply. You have ${current(state).gold} Gold.</p><div id="vError" class="vError" hidden></div><input id="buyAmount" type="number" min="1" max="5" value="1" aria-label="Supply amount"><button data-buy>Buy Supply & end turn</button></div>`);
 if(name==='black')return modal('Black Market','<p>Refresh the Crew Market, then recruit one Crew for 1 Gold less. Refresh commits your main action.</p><button data-refresh>Refresh market</button>');
 if(name==='quarters')return modal('Crew Quarters',`<p>Ready up to 2 exhausted Crew.</p><div class="vSelect">${current(state).crew.filter(x=>x.exhausted).map(x=>`<label><input type="checkbox" name="readyCrew" value="${x.uid}">${esc(CARDS[x.id].name)}</label>`).join('')||'No exhausted Crew.'}</div><button data-ready>Ready selected Crew</button>`);
 if(name==='witch')return modal('Sea Witch',`<p>Pay 2 Gold for a blessing on your next Expedition. One blessing at a time.</p><div class="vToolbar">${[['wind','Fair Winds · −1 Supply'],['war','War Spirit · +1 Power'],['sight','Keen Sight · inspect lower Mission'],['fortune','Fortune · reroll one non-Skull die']].map(([id,t])=>`<button data-bless="${id}">${t}</button>`).join('')}</div>`);
}
root.addEventListener('click',ev=>{const m=ev.target.closest('[data-mission]');if(m)return prep(m.dataset.mission);const b=ev.target.closest('[data-v]');if(b)action(b.dataset.v)});
body.addEventListener('click',ev=>{const b=ev.target.closest('button');if(!b)return;const d=b.dataset;
 if(d.mission)return prep(d.mission);if(d.recruit)return doAct({type:'recruit',id:d.recruit,pool:d.pool});if('work'in d)return doAct({type:'work'});if('buy'in d)return doAct({type:'market',amount:Number(body.querySelector('#buyAmount').value)});if('refresh'in d)return doAct({type:'blackRefresh'});if('blackSkip'in d)return doAct({type:'blackSkip'});if('ready'in d)return doAct({type:'ready',ids:[...body.querySelectorAll('[name=readyCrew]:checked')].map(x=>x.value)});if(d.bless)return doAct({type:'bless',id:d.bless});
 if(d.launch)return doAct({type:'launch',mission:d.launch,crew:[...body.querySelectorAll('[name=sCrew]:checked')].map(x=>x.value),treasures:[...body.querySelectorAll('[name=sTreasure]:checked')].map(x=>x.value),approach:body.querySelector('#approach')?.value||'skip',sacrifice:body.querySelector('#sacrifice')?.value,powder:body.querySelector('#powder')?.checked});
 if(d.e)return doAct({type:d.e});if(d.control)return doAct({type:'control',id:d.control,index:Number(d.index)});if(d.protect)return doAct({type:'loss',prevent:d.protect});if(d.loss)return doAct({type:'loss',uid:d.loss});if(d.keep)return doAct({type:'keepTreasure',id:d.keep});
 if(d.category){body.querySelector('#collection').innerHTML=DATA.cards.filter(c=>c.kind===d.category).map(c=>card(c.id)).join('');return}
 if(d.peek){const c=CARDS[d.peek],st=c.zone?state.stacks[c.zone].find(st=>st[0]===c.id):null;if(st?.[1]){modal('Lower Mission preview',card(st[1],`<button data-mission="${c.id}">Return to preparation</button>`))}else toast('No lower normal Mission is available to inspect.')}
});
function scheduleAI(){clearTimeout(aiTimer);if(root.hidden||state?.status!=='playing'||state?.mode!=='ai'||state.turn!==1)return;aiTimer=setTimeout(aiStep,900)}
function aiStep(){if(root.hidden||state.turn!==1)return;const p=current(state),e=state.exp;let a;
 if(e){if(e.phase==='ready')a={type:'roll'};else if(e.phase==='dice'){const opts=controls(state);a=opts.length?{type:'control',id:opts[0],index:0}:{type:'resolve'}}else if(e.phase==='loss'){const crew=p.crew.filter(x=>e.crew.includes(x.uid));a=crew.some(x=>x.id==='C12'&&!x.exhausted)?{type:'loss',prevent:'surgeon'}:e.treasures.includes('T19')?{type:'loss',prevent:'medallion'}:{type:'loss',uid:(crew.find(x=>x.id==='C11')||crew.sort((a,b)=>CARDS[a.id].power-CARDS[b.id].power)[0]).uid}}else if(e.phase==='treasure')a={type:'keepTreasure',id:e.choices[0]};else a={type:'finish'}}
 else{const crew=p.crew.filter(x=>!x.exhausted).sort((a,b)=>CARDS[b.id].power-CARDS[a.id].power).slice(0,4).map(x=>x.uid),treasures=p.treasures.slice(0,3);const exhausted=p.crew.filter(x=>x.exhausted).slice(0,2).map(x=>x.uid);const ids=[...Object.values(state.stacks).flat().filter(st=>st.length).map(st=>st[0]),state.final[0]].filter(Boolean);const missions=ids.filter(id=>available(state,id)).map(id=>({id,e:{mission:id,crew,treasures},z:CARDS[id].zone||4})).filter(x=>crew.length&&p.supply>=supplyCost(p,x.z,treasures)&&basePower(p,x.e)>=CARDS[x.id].target-2).sort((a,b)=>b.z-a.z);const recruitable=[...state.veteranMarket,...state.market].filter(id=>CARDS[id].cost<=p.gold&&(p.crew.length<4||CARDS[id].power>Math.min(...crew.map(uid=>CARDS[p.crew.find(c=>c.uid===uid).id].power)))).sort((a,b)=>CARDS[b].power-CARDS[a].power);
 if(missions.length){const m=missions[0];a={type:'launch',mission:m.id,crew,treasures,approach:CARDS[m.id].kind==='final'&&finalOptions(p,m.e).check?'check':'skip'}}else if(exhausted.length)a={type:'ready',ids:exhausted};else if(recruitable.length)a={type:'recruit',id:recruitable[0],pool:state.veteranMarket.includes(recruitable[0])?'veteran':'common'};else if(p.gold>0&&p.supply<9)a={type:'market',amount:Math.min(5,p.gold)};else a={type:'work'};}
 doAct(a);
}
window.addEventListener('captainsdash:startgame',ev=>{try{const saved=ev.detail.resume?JSON.parse(localStorage.getItem(SAVE_KEY)||'null'):null;state=saved?.version==='rules-0.8.1'?saved:newGame(ev.detail);document.querySelector('#transition').classList.remove('show');save();render();if(state.exp&&state.status==='playing')showExp();scheduleAI()}catch(err){toast('Could not load voyage: '+err.message)}});
