import {banter,hat,workerHtml,animateWorker,resultFlash,finale,guideGallery} from './voyage-flair.js';
import {DATA,CARDS,SAVE_KEY,LOCATIONS,newGame,current,unlocked,locationOpen,legalWorker,available,act,testInfo,baseScore,totalScore,supplyCost,controls} from './engine-v014.mjs';
const root=document.querySelector('#voyage'),dlg=document.querySelector('#voyageDialog'),body=document.querySelector('#voyageBody');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const colors=['#df4a3f','#4598ef','#46b879','#e9c65b'],icons={Combat:'⚔',Sailing:'⚓',Search:'⌕'};
const positions={1:[[47.8,59.7,7.4,10.3],[56.3,59.7,7.4,10.3],[64.7,59.7,7.4,10.3]],2:[[42.5,39.2,7.2,10.3],[51.2,39.2,7.2,10.3],[59.8,39.2,7.2,10.3]],3:[[48.1,17.5,7.5,10.4],[58.2,17.5,7.5,10.4]],4:[[83,14.4,9.3,15.5]]};
const places=Object.keys(LOCATIONS).map((id,i)=>({id,x:2.8+(i%4)*8.8,y:i<4?63.9:73.7}));
let busy=false;
const isAITurn=()=>state?.mode==='ai'&&state.turn===1&&state.status==='playing';
let state=null,zoom=false,aiTimer=null,guidePage=1;
const lines=t=>esc(t).replaceAll('\n','<br>');
function art(c){const a=c.art;return `<div class="art" role="img" aria-label="${esc(c.name)}" style="aspect-ratio:${a.width}/${a.height};background-image:url('assets/v08-${a.sheet}.png');background-size:${a.sourceWidth/a.width*100}% ${a.sourceHeight/a.height*100}%;background-position:${a.x/(a.sourceWidth-a.width)*100}% ${a.y/(a.sourceHeight-a.height)*100}%"></div>`}
function details(c){if(c.kind==='crew')return `<div class="vStats">${Object.entries(c.stats).map(([t,v])=>`<span>${icons[t]} ${t}<b>${v}</b></span>`).join('')}</div><p>${esc(c.tier)} · ${c.cost} Gold</p><p>${lines(c.text)}</p>`;if(c.kind==='treasure')return `<b>${esc(c.type)} · Passive</b><p>${lines(c.text)}</p>`;if(c.kind==='final')return c.steps.map((s,i)=>`<section class="testPanel"><b>Step ${i+1} · ${esc(s.name)}</b><p>${lines(s.text)}</p></section>`).join('')+'<p>9 Supply · 3 dice per test · Win both tests to win the game.</p>';return `<div class="vStats"><span>${icons[c.test]} ${c.test}</span><span>Target <b>${c.target}</b></span></div><p>${[1,3,6][c.zone-1]} Supply · ${c.zone} dice</p><div class="reward"><b>Success</b><p>${lines(c.text)}</p></div>`}
function card(id,extra=''){const c=CARDS[id];return `<article class="vCard"><h3>${esc(c.name)}</h3>${art(c)}<div class="text">${details(c)}${extra}</div></article>`}
function button(action,label,attrs=''){return `<button data-action="${action}" ${attrs}>${label}</button>`}
function toast(t){const el=document.querySelector('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3500)}
function modal(title,html,locked=false){body.onchange=null;document.querySelector('#voyageTitle').textContent=title;body.innerHTML='<p id="vError" class="vError" hidden></p>'+html;document.querySelector('#voyageClose').hidden=locked;dlg.dataset.locked=String(locked);if(!dlg.open)dlg.showModal();dlg.scrollTop=0}
document.querySelector('#voyageClose').onclick=()=>dlg.close();dlg.addEventListener('cancel',ev=>{if(dlg.dataset.locked==='true')ev.preventDefault()});
function save(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(state));window.dispatchEvent(new Event('captainsdash:saved'))}catch{toast('Storage is full. Keep this tab open to continue this voyage.')}}
function doAct(a){if(busy)return false;try{const previous=state;state=act(state,a);if(state.exp){const c=CARDS[state.exp.mission];state.exp.boardSlot=previous.exp?.mission===state.exp.mission?previous.exp.boardSlot:Math.max(0,(previous.stacks[c.zone]||[]).findIndex(st=>st[0]===c.id))}save();render();const complete=()=>{busy=false;showPending();if(state.status!=='won'&&state.exp){const e=state.exp,old=previous.exp;if(e.phase==='loss'&&old?.phase!=='loss')resultFlash(dlg,false);else if(e.success===true&&old?.success!==true)resultFlash(dlg,true);else if(old&&e.step>old.step)resultFlash(dlg,true,true)}scheduleAI()};if(a.type==='worker'){busy=true;animateWorker(root,a.location,previous.phase,complete)}else complete();return true}catch(e){busy=false;const el=body.querySelector('#vError');if(dlg.open&&el){el.hidden=false;el.textContent=e.message}else toast(e.message);return false}}
function playerDock(){return '<section class="playerDock" aria-label="All captains">'+state.players.map((p,i)=>`<button class="playerPanel ${i===state.turn?'active':''}" data-action="player" data-index="${i}" style="--captain:${colors[i]}" aria-label="View ${esc(p.name)} crew and treasures"><strong>${esc(p.name)} ${i===state.turn?'<small>YOUR TURN</small>':''}</strong><div class="playerNumbers"><span>🪙 <b>${p.gold}</b> Gold</span><span>▣ <b>${p.supply}</b> Supply</span><span>♟ <b>${p.crew.length}/4</b> Crew</span><span>◆ <b>${p.treasures.length}/3</b> Treasure</span></div><div class="miniRoster">${p.crew.map(c=>`<span title="${esc(CARDS[c.id].name)}" class="${c.exhausted?'exhausted':''}">${art(CARDS[c.id])}</span>`).join('')||'<small>No Crew aboard</small>'}${p.treasures.map(id=>`<span title="${esc(CARDS[id].name)}">${art(CARDS[id])}</span>`).join('')}</div></button>`).join('')+'</section>'}

function render(){root.hidden=false;document.querySelector('#app').hidden=true;const p=current(state);if(state.status==='won'){root.innerHTML=finale(state,CARDS,art,esc,button);return}
 let slots='';for(const z of [1,2,3,4]){const stacks=z===4?[state.final]:state.stacks[z];stacks.forEach((st,i)=>{const [x,y,w,h]=positions[z][i],c=CARDS[st[0]];slots+=`<button class="vSlot ${unlocked(state,z)?'':'locked'}" style="left:${x}%;top:${y}%;width:${w}%;height:${h}%" data-mission="${st[0]||''}" ${!c?'disabled':''} aria-label="${c?esc(c.name):'Stack complete'}">${c?art(c):''}<span class="slotInfo">${!unlocked(state,z)?'🔒':c?`${c.test?icons[c.test]+' '+c.target:'2 TESTS'}`:'COMPLETE'}</span></button>`})}
 let token={x:18,y:88};if(state.exp){const c=CARDS[state.exp.mission],z=c.zone||4,i=z===4?0:(state.exp.boardSlot??Math.max(0,state.stacks[z].findIndex(st=>st[0]===c.id)));token={x:positions[z][i][0]-4,y:positions[z][i][1]+3}}
 root.innerHTML=`<header class="vHud"><h1>Captain’s Dash <small>The Final Isle · v0.15.2</small></h1><div class="resources" style="color:${colors[state.turn]}">${esc(p.name)}</div>${button('crew','Crew')}${button('help','Guide')}<button data-music-toggle aria-label="Toggle music">♫ Music</button>${button('tools','☰','aria-label="Game options"')}</header><div class="vProgress"><span>Zone II: ${unlocked(state,2)?'OPEN':state.progress[0]+'/2'}</span><span>Zone III: ${unlocked(state,3)?'OPEN':state.progress[1]+'/2'}</span><span>Final Isle: ${unlocked(state,4)?'OPEN':state.progress[2]+'/1'}</span></div><div class="turnPrompt">${isAITurn()?'Blackbeard is thinking · ':''}Round ${state.round} · ${state.location?'Resolve '+LOCATIONS[state.location]:state.phase==='place'?'Place a Pirate':'Take a Pirate'}${state.location?button('resume','Resume action'):''}</div><div class="vBoardScroll"><div class="vBoard ${zoom?'zoomed':''}"><img src="assets/v08-board.png" alt="Captain’s Dash archipelago map">${slots}${places.map(({id,x,y})=>`<button class="vAction workerSpot ${legalWorker(state,id)?'legal '+state.phase:!locationOpen(state,id)?'sealed':'unavailable'}" style="left:${x}%;top:${y}%;width:8.2%;height:9.4%;--owner:#bda16a" data-worker="${id}" ${legalWorker(state,id)?'':'disabled'} aria-label="${LOCATIONS[id]} ${state.workers[id]===null?'empty':'shared Pirate'}">${!locationOpen(state,id)?'<span class="spotStatus" aria-hidden="true">🔒</span>':workerHtml(state,id,LOCATIONS[id])}</button>`).join('')}<div class="token" style="--player:#bda16a;left:${token.x}%;top:${token.y}%">${hat()}</div><div class="finalCost">9 SUPPLY · TWO TESTS</div><div class="finalCount" aria-label="${state.final.length} Final cards left">${Array.from({length:3},(_,i)=>`<span class="${i>=state.final.length?'used':''}"></span>`).join('')}</div><div class="crewMarketMask" aria-label="Crew market: 3 cards">${state.market.map(id=>`<button class="marketPortrait" data-action="inspect" data-id="${id}" aria-label="Inspect ${esc(CARDS[id].name)}">${art(CARDS[id])}<span>${esc(CARDS[id].name)} · ${CARDS[id].cost}G</span></button>`).join('')}</div><div class="mapCredit">Designed by Thanead Chiawchanlikit</div></div></div>${playerDock()}<div class="vFoot"><div class="workerActions">${Object.keys(LOCATIONS).map(id=>`<button data-worker="${id}" ${legalWorker(state,id)?'':'disabled'}>${LOCATIONS[id]}${!locationOpen(state,id)?' 🔒':''}</button>`).join('')}</div>${button('zoom',zoom?'Fit board':'Zoom board')}${button('cards','All 81 cards')}${button('history','History')}${button('help','Help / Game Guide')}</div>`;
}
function showPending(){if(state.status==='won'){dlg.close();return}if(state.overflow){const p=current(state),crew=state.overflow==='crew';modal(crew?'Keep up to 4 Crew':'Keep up to 3 Treasures',`<p>Choose one owned card to discard before continuing.</p><div class="vGrid">${(crew?p.crew:p.treasures.map(id=>({id,uid:id}))).map(c=>card(c.id,button('discardOwned','Discard',`data-id="${c.uid}"`))).join('')}</div>`,true);return}if(state.exp)return showExp();if(state.location)return showLocation();dlg.close()}
function showLocation(){const l=state.location,p=current(state),skip=button(state.blackRefreshed?'blackSkip':'skip','Finish without using this action');let html='';
 if(['tavern','veteran','black'].includes(l)){const ids=l==='veteran'?state.veteranMarket:state.market;if(l==='black'&&!state.blackRefreshed)html=`<p>Select up to 3 cards to refresh, then recruit at 1 Gold less.</p><div class="vGrid">${ids.map(id=>card(id,`<label><input type="checkbox" name="refresh" value="${id}"> Refresh</label>`)).join('')}</div>${button('refresh','Refresh selected cards')}`;else html=`<p>Recruit 1 Crew${l==='black'?' at 1 Gold less':''}. Maximum 4 owned; choose a discard if exceeded.</p><div class="vGrid">${ids.map(id=>card(id,button('recruit',`Recruit · ${Math.max(0,CARDS[id].cost-(l==='black'?1:0))} Gold`,`data-id="${id}"`))).join('')}</div>`}
 if(l==='market')html=`<p>Buy up to 5 Supply at 1 Gold each. You have ${p.gold} Gold.</p><input type="number" id="amount" min="1" max="5" value="1" aria-label="Supply amount">${button('market','Buy Supply')}`;
 if(l==='work')html='<p>Gain 3 Gold.</p>'+button('work','Gain 3 Gold');
 if(l==='quarters')html=`<p>Ready up to 4 exhausted Crew.</p>${p.crew.filter(c=>c.exhausted).map(c=>`<label><input type="checkbox" name="ready" value="${c.uid}">${esc(CARDS[c.id].name)}</label>`).join('')||'<p>No exhausted Crew.</p>'}${button('ready','Ready selected Crew')}`;
 if(l==='witch')html='<p>Pay 3 Gold for your next Expedition. A new blessing replaces your current blessing.</p>'+['Combat','Sailing','Search','fortune'].map(id=>button('bless',id==='fortune'?'Fortune · reroll 1 non-Skull die':'+3 '+id,`data-id="${id}"`)).join('');
 if(l==='dock')html=`<p>Choose any face-up Mission in an unlocked Zone. Supply: 1 / 3 / 6 / 9.</p><div class="vGrid">${[...Object.values(state.stacks).flat().filter(st=>st.length).map(st=>st[0]),state.final[0]].filter(id=>available(state,id)).map(id=>card(id,`<button data-mission="${id}">Prepare Expedition</button>`)).join('')}</div>`;
 modal(LOCATIONS[l],'<p class="pirateBanter">“'+banter[l]+'”</p>'+html+'<div class="vToolbar">'+skip+'</div>');
}
function prep(id){if(state.exp)return showExp();if(state.location!=='dock'){modal(CARDS[id].name,card(id)+'<p>Place or take a Pirate at Dock to launch an Expedition.</p>');return}if(!available(state,id))return toast('Zone locked.');const c=CARDS[id],p=current(state),peek=p.crew.some(c=>c.id==='C13'&&!c.exhausted)||p.treasures.includes('T01');
 modal('Prepare Expedition',`<div class="vSplit">${card(id)}<div class="vForm"><h3>Select ready Crew</h3>${p.crew.map(x=>`<label><input type="checkbox" name="crew" value="${x.uid}" ${x.exhausted?'disabled':'checked'}>${esc(CARDS[x.id].name)} · ${Object.entries(CARDS[x.id].stats).map(([t,v])=>icons[t]+v).join(' / ')}</label>`).join('')}<p>All ${p.treasures.length} owned Treasure passives apply.</p>${c.id==='F3'?`<p>Step 1 cost</p><select id="payment"><option value="gold">Pay 6 Gold</option><option value="treasure">Discard 1 Treasure</option></select><select id="sacrifice" aria-label="Treasure to discard">${p.treasures.map(id=>`<option value="${id}">${esc(CARDS[id].name)}</option>`).join('')}</select>`:''}${p.treasures.includes('T07')&&(c.test==='Combat'||c.steps?.some(st=>st.test==='Combat'))?'<label><input type="checkbox" id="powder"> Black Powder Horn: +1 Supply for +2 Combat</label>':''}<div id="previewCost" class="vSummary"></div>${button('launch','Pay & launch',`data-id="${id}"`)}${peek?button('peek','Look beneath this stack',`data-id="${id}"`):''}${button('resume','Back to Missions')}</div></div>`);
 const update=()=>{const crew=[...body.querySelectorAll('[name=crew]:checked')].map(x=>x.value),treasures=p.treasures.filter(t=>!(c.id==='F3'&&body.querySelector('#payment').value==='treasure'&&body.querySelector('#sacrifice').value===t)),e={mission:id,crew,treasures,step:0,blessing:p.blessing,powder:!!body.querySelector('#powder')?.checked};body.querySelector('#previewCost').textContent=`${crew.length}/4 Crew · ${testInfo(e).test} ${baseScore(p,e)} before dice · ${supplyCost(p,c.zone||4,treasures,crew)+(e.powder?1:0)} Supply${c.id==='F3'&&body.querySelector('#payment').value==='gold'?' + 6 Gold':''}`;let reason='';try{act(state,{type:'launch',mission:id,crew,payment:body.querySelector('#payment')?.value,sacrifice:body.querySelector('#sacrifice')?.value,powder:e.powder})}catch(err){reason=err.message}const launch=body.querySelector('[data-action=launch]');launch.disabled=!!reason;launch.textContent=reason||'Pay & launch';if(c.kind==='final')body.querySelector('#previewCost').textContent+=` · Step 2: ${c.steps[1].test} ${baseScore(p,{...e,step:1})} / ${c.steps[1].target}`};body.onchange=update;update();
}
function showExp(){body.onchange=null;const e=state.exp,p=current(state),info=testInfo(e);let html=`<p>${esc(CARDS[e.mission].name)}${CARDS[e.mission].kind==='final'?' · Step '+(e.step+1)+' of 2':''} · ${e.paid} Supply paid</p><h3>${icons[info.test]} ${info.test} · Target ${info.target}</h3>`;
 if(e.phase==='ready')html+=`<p>Relevant Crew + passives: ${baseScore(p,e)}</p>${button('roll',`Roll ${CARDS[e.mission].zone||3} dice`)}`;
 else {html+=`<div class="dice">${e.dice.map(d=>`<div class="die">${d==='SKULL'?'☠':d==='GOLD'?'🪙':d}</div>`).join('')}</div><p>Total: ${totalScore(p,e)} / ${info.target}${e.dice.includes('SKULL')?' · SKULL — immediate failure':''}</p>`;
 if(e.phase==='dice'){html+=controls(state).map(o=>o.id==='fortune'?e.dice.map((d,i)=>button('control','Fortune: reroll die '+(i+1),`data-id="fortune" data-index="${i}"`)).join(''):button('control',esc(o.label),`data-id="${o.id}"`)).join('')+button('resolve','Resolve test')}
 if(e.phase==='loss'){html+='<p>Choose 1 participating Crew to discard, or use protection.</p>';if(p.crew.some(c=>c.id==='C12'&&e.crew.includes(c.uid)&&!c.exhausted))html+=button('protect','Surgeon · prevent Crew loss','data-id="surgeon"');if(e.treasures.includes('T19'))html+=button('protect','Discard Captain’s Medallion','data-id="medallion"');html+=p.crew.filter(c=>e.crew.includes(c.uid)).map(c=>button('loss','Discard '+esc(CARDS[c.id].name),`data-id="${c.uid}"`)).join('')}
 if(e.phase==='treasure')html+='<p>Choose the drawn Treasure to keep.</p><div class="vGrid">'+e.choices.map(id=>card(id,button('keepTreasure','Keep',`data-id="${id}"`))).join('')+'</div>';
 if(e.phase==='result')html+=`<h3>${e.success?'MISSION CONQUERED!':'THE SEA BITES BACK!'}</h3><p>${e.success?lines(CARDS[e.mission].text||'Victory'): 'Crew loss resolved. Supply stays spent.'}</p>${button('finish','Return to Pirate Haven')}`;
 }modal('Expedition',html,true);
}
function showGuide(){modal('Help · Game Guide',guideGallery())}
function action(name,d={}){if(busy)return;if(name==='tools'){modal('Captain’s table',`<div class="vToolbar">${button('resume','Back to voyage')}${button('zoom',zoom?'Fit board':'Enlarge board')}${button('cards','Card library')}${button('history','Voyage history')}${button('help','Game guide')}${button('menu','Main menu')}</div><p>Place a Pirate on a glowing empty location, complete its action, then take a Pirate from a different location and complete that action.</p>`);return;}if(name==='replayEnding'){render();return}if(name==='inspect'){modal(CARDS[d.id].name,card(d.id));return}if(name==='player'){const p=state.players[+d.index];modal(p.name+' · Crew & Treasure','<h3>Crew</h3><div class="vGrid">'+(p.crew.map(c=>card(c.id,'<p>'+(c.exhausted?'Exhausted':'Ready')+'</p>')).join('')||'<p>No Crew aboard.</p>')+'</div><h3>Treasure</h3><div class="vGrid">'+(p.treasures.map(id=>card(id)).join('')||'<p>No Treasure yet.</p>')+'</div>');return}if(name==='help'||name==='guide'){if(d.id)guidePage=+d.id;showGuide();return}if(name==='menu'){clearTimeout(aiTimer);dlg.close();root.hidden=true;document.querySelector('#app').hidden=false;return}if(name==='zoom'){zoom=!zoom;dlg.close();render();return}if(name==='resume')return showPending();if(name==='crew'){const p=current(state);modal('Crew & Treasure','<div class="vGrid">'+p.crew.map(c=>card(c.id,`<p>${c.exhausted?'Exhausted':'Ready'}</p>`)).concat(p.treasures.map(id=>card(id))).join('')+'</div>');return}if(name==='history'){modal('Voyage History',state.log.map(t=>'<p>'+esc(t)+'</p>').join('')||'<p>Your voyage has just begun.</p>');return}if(name==='cards'){modal('All 81 cards · v0.15 Final','<div class="vGrid">'+DATA.cards.map(c=>card(c.id)).join('')+'</div>');return}
 if(name==='peek'){const c=CARDS[d.id],stack=c.zone?state.stacks[c.zone].find(st=>st[0]===d.id):state.final;modal('Hidden Mission',stack?.[1]?card(stack[1])+`<button data-mission="${d.id}">Back to preparation</button>`:'<p>No lower card in this stack.</p>');return}
 const a={type:name,id:d.id};if(name==='protect'){a.type='loss';a.prevent=d.id}if(name==='control')a.index=+d.index;if(name==='market')a.amount=+body.querySelector('#amount').value;if(name==='ready'||name==='refresh')a.ids=[...body.querySelectorAll(`[name=${name}]:checked`)].map(x=>x.value);if(name==='launch')Object.assign(a,{mission:d.id,crew:[...body.querySelectorAll('[name=crew]:checked')].map(x=>x.value),payment:body.querySelector('#payment')?.value,sacrifice:body.querySelector('#sacrifice')?.value,powder:!!body.querySelector('#powder')?.checked});doAct(a);
}
function click(ev){if(busy)return;const b=ev.target.closest('button');if(!b)return;if(isAITurn()&&(b.dataset.worker||b.dataset.mission||!['tools','menu','help','history','cards','crew','player','inspect','zoom','resume','guide'].includes(b.dataset.action)))return toast('Blackbeard is taking this turn.');if(b.dataset.worker)return doAct({type:'worker',location:b.dataset.worker});if(b.dataset.mission)return prep(b.dataset.mission);if(b.dataset.action)action(b.dataset.action,b.dataset)}
root.addEventListener('click',click);body.addEventListener('click',click);
document.addEventListener('click',ev=>{const b=ev.target.closest('[data-guide-page]');if(b){guidePage=+b.dataset.guidePage;showGuide()}});
function scheduleAI(){clearTimeout(aiTimer);if(!root.hidden&&state.status==='playing'&&state.mode==='ai'&&state.turn===1)aiTimer=setTimeout(aiStep,650)}
function aiStep(){const p=current(state),e=state.exp;let a;if(state.overflow)a={type:'discardOwned',id:state.overflow==='crew'?[...p.crew].sort((a,b)=>Object.values(CARDS[a.id].stats).reduce((x,y)=>x+y)-Object.values(CARDS[b.id].stats).reduce((x,y)=>x+y))[0].uid:p.treasures[0]};else if(e){if(e.phase==='ready')a={type:'roll'};else if(e.phase==='dice'){const o=controls(state)[0];a=o?{type:'control',id:o.id,index:e.dice.indexOf(0)>=0?e.dice.indexOf(0):0}:{type:'resolve'}}else if(e.phase==='loss')a=p.crew.some(c=>e.crew.includes(c.uid)&&c.id==='C12')?{type:'loss',prevent:'surgeon'}:e.treasures.includes('T19')?{type:'loss',prevent:'medallion'}:{type:'loss',id:(p.crew.find(c=>e.crew.includes(c.uid)&&c.id==='C10')||p.crew.find(c=>e.crew.includes(c.uid))).uid};else if(e.phase==='treasure')a={type:'keepTreasure',id:e.choices[0]};else a={type:'finish'}}else if(!state.location){const ids=Object.keys(LOCATIONS).filter(l=>legalWorker(state,l)),order=p.crew.length<3&&p.gold>=3?['veteran','tavern','black','work','market','dock','quarters','witch']:p.supply<(unlocked(state,4)?9:unlocked(state,3)?6:3)?(p.gold?['market','work','dock','tavern','quarters','black','witch','veteran']:['work','dock','tavern','quarters','market','black','witch','veteran']):['dock','veteran','work','market','tavern','quarters','witch','black'];a={type:'worker',location:order.find(l=>ids.includes(l))}}else{const l=state.location;if(l==='work')a={type:'work'};else if(l==='market'&&p.gold)a={type:'market',amount:Math.min(5,p.gold)};else if(['tavern','veteran','black'].includes(l)){if(l==='black'&&!state.blackRefreshed)a={type:'refresh',ids:state.market};else{const id=(l==='veteran'?state.veteranMarket:state.market).find(id=>CARDS[id].cost-(l==='black'?1:0)<=p.gold);a=id?{type:'recruit',id}:{type:l==='black'?'blackSkip':'skip'}}}else if(l==='dock'){const crew=p.crew.filter(c=>!c.exhausted).map(c=>c.uid);const ids=[...Object.values(state.stacks).flat().map(st=>st[0]),state.final[0]].filter(id=>id&&available(state,id));const id=ids.filter(id=>{const c=CARDS[id],e={mission:id,crew,treasures:p.treasures,step:0,blessing:p.blessing};return crew.length&&p.supply>=supplyCost(p,c.zone||4)&&baseScore(p,e)>=testInfo(e).target-2&&(id!=='F3'||p.gold>=6)&&(id!=='F4'||p.crew.length===4&&p.crew.filter(x=>CARDS[x.id].tier==='Veteran').length>=2&&p.treasures.length>=2)&&(id!=='F5'||new Set(p.crew.map(c=>c.id)).size>=3&&p.crew.some(x=>CARDS[x.id].tier==='Veteran'))}).sort((a,b)=>(CARDS[b].zone||4)-(CARDS[a].zone||4))[0];if(id)a={type:'launch',mission:id,crew}}if(!a)a={type:'skip'}}if(a&&!doAct(a))toast('AI action could not complete. Resume the action manually.');}
window.addEventListener('captainsdash:startgame',ev=>{try{const saved=ev.detail.resume?JSON.parse(localStorage.getItem(SAVE_KEY)||'null'):null;state=saved?.version==='0.15'?saved:newGame(ev.detail);document.querySelector('#transition').classList.remove('show');save();render();showPending();scheduleAI()}catch(err){document.querySelector('#transition').classList.remove('show');toast('Could not start: '+err.message)}});
