import assert from 'node:assert/strict';
import {DATA,CARDS,newGame,instance,act,current,controls,basePower} from '../engine-v08.mjs';
let passed=0;function test(name,fn){try{fn();passed++;}catch(e){console.error('FAIL',name);throw e}}
function fixture(id,crew=['C11','C14','C15','C09'],treasures=['T01','T02','T06']){let s=newGame({players:4},()=>.6);s.progress=[2,3,1];const p=current(s);p.gold=100;p.supply=100;p.crew=crew.map(id=>instance(s,id));p.treasures=treasures;const c=CARDS[id];if(c.zone)s.stacks[c.zone][0]=[id,'Z1-03'];else s.final=[id,'F8'];return s}
function launch(s,id,extra={}){return act(s,{type:'launch',mission:id,crew:current(s).crew.map(c=>c.uid),treasures:current(s).treasures,...extra})}
function roll(s,faces){let i=0;return act(s,{type:'roll'},()=>faces[i++]/6+.001)}
function settle(s){if(s.exp.phase==='dice')s=act(s,{type:'resolve'});if(s.exp.phase==='loss')s=act(s,{type:'loss',uid:current(s).crew.find(c=>c.id==='C11')?.uid||current(s).crew[0].uid});while(s.exp.phase==='treasure')s=act(s,{type:'keepTreasure',id:s.exp.choices[0]});return s}
test('84 cards, exact pools',()=>{assert.equal(DATA.cards.length,84);assert.equal(DATA.cards.filter(c=>c.kind==='final').length,8)});
test('starting bonuses and stacks',()=>{const s=newGame({players:4});assert.deepEqual(s.players.map(p=>[p.gold,p.supply,p.crew.length]),[[3,4,2],[4,4,2],[4,5,2],[4,5,2]]);assert.deepEqual(Object.values(s.stacks).map(st=>st.length),[3,3,2]);assert.equal(s.final.length,5)});
for(const c of DATA.cards.filter(c=>c.zone||c.kind==='final')){
 test(c.id+' success',()=>{let s=fixture(c.id);s=settle(roll(launch(s,c.id),[4,4,4]));assert.equal(s.exp.success,true);if(c.kind==='final')assert.equal(s.status,'won');else assert.equal(s.missionDiscard[0].id,c.id)});
 test(c.id+' skull failure',()=>{let s=fixture(c.id);s=settle(roll(launch(s,c.id),[0,5,5]));assert.equal(s.exp.success,false);assert.equal(current(s).crew.length,3);if(c.kind==='final')assert.equal(s.final[0],'F8');else assert.equal(s.stacks[c.zone][0][0],c.id)});
}
test('gold collected despite Skull',()=>{let s=fixture('Z2-01',['C01','C01'],[]);s=roll(launch(s,'Z2-01'),[0,5]);assert.equal(current(s).gold,101);assert.equal(s.exp.phase,'loss');assert.deepEqual(controls(s),[]);assert.throws(()=>act(s,{type:'control',id:'fortune',index:0}))});
test('failure penalty prevented by Surgeon and Quartermaster refund',()=>{let s=fixture('Z3-01',['C12','C08','C01'],[]);s=roll(launch(s,'Z3-01'),[0,1,1]);s=act(s,{type:'loss',prevent:'surgeon'});assert.equal(current(s).crew.length,3);assert.equal(current(s).supply,97);assert.equal(current(s).crew[0].exhausted,true)});
test('lost Quartermaster still refunds and lost Smuggler refunds',()=>{for(const id of ['C08','C06']){let s=fixture('Z3-01',[id],[]);s=roll(launch(s,'Z3-01'),[0,1,1]);s=act(s,{type:'loss',uid:current(s).crew[0].uid});assert.equal(current(s).supply,id==='C08'?97:95)}});
test('one Dice Control, numerical success and no repeat',()=>{let s=fixture('Z1-01',['C07','C01'],['T13']);s=roll(launch(s,'Z1-01'),[1]);s=act(s,{type:'control',id:'C07'});assert.throws(()=>act(s,{type:'control',id:'T13'}));s=act(s,{type:'resolve'});assert.equal(s.exp.success,true)});
test('Sharpshooter adds one while preserving its existing Power',()=>{let s=fixture('Z1-01',['C09'],[]);s=roll(launch(s,'Z1-01'),[1]);assert(controls(s).includes('C09'));s=act(s,{type:'control',id:'C09'});s=settle(s);assert.equal(s.exp.total,4);s=act(s,{type:'finish'});assert.equal(s.players[0].crew[0].exhausted,true)});
test('final check is optional; sacrifice reduces participating Power',()=>{let s=fixture('F2');const uid=current(s).crew[0].uid;s=launch(s,'F2',{approach:'sacrifice',sacrifice:uid});assert.equal(s.exp.edge,1);assert.equal(s.exp.crew.length,3);assert.equal(current(s).crew.length,3)});
test('failed launch is atomic, no sacrifice on insufficient payment',()=>{let s=fixture('F2');s.players[0].supply=0;const before=JSON.stringify(s);assert.throws(()=>launch(s,'F2',{approach:'sacrifice',sacrifice:current(s).crew[0].uid}));assert.equal(JSON.stringify(s),before)});
test('Final fifth failure = shared loss',()=>{let s=fixture('F8');s.final=['F8'];s=settle(roll(launch(s,'F8'),[0,0,0]));assert.equal(s.status,'shared_loss');assert.equal(s.final.length,0)});
test('serialized paid expedition resumes without recharging/rerolling',()=>{let s=fixture('F1');s=roll(launch(s,'F1'),[4,4,4]);const supply=current(s).supply;s=JSON.parse(JSON.stringify(s));assert.throws(()=>act(s,{type:'roll'}));s=settle(s);assert.equal(current(s).supply,supply)});
test('unlocked threshold, empty stack does not refill',()=>{let s=fixture('Z1-01');s.progress=[1,0,0];s.stacks[1][0]=['Z1-01'];s=settle(roll(launch(s,'Z1-01'),[4]));assert.equal(s.progress[0],2);assert.deepEqual(s.stacks[1][0],[])});
test('Treasure Hunter offers two and discards unchosen',()=>{let s=fixture('Z1-02',['C10','C14'],[]);s=roll(launch(s,'Z1-02'),[4]);s=act(s,{type:'resolve'});assert.equal(s.exp.phase,'treasure');assert.equal(s.exp.choices.length,2);const [take,discard]=s.exp.choices;s=act(s,{type:'keepTreasure',id:take});assert(current(s).treasures.includes(take));assert(s.treasureDiscard.includes(discard))});
test('Black Market commits one action and discounted recruit',()=>{let s=newGame({players:2});s=act(s,{type:'blackRefresh'},()=>.5);assert.equal(s.turn,0);assert.throws(()=>act(s,{type:'work'}));const id=s.market.find(id=>CARDS[id].cost<=4);const gold=current(s).gold;s=act(s,{type:'recruit',id});assert.equal(s.turn,1);assert.equal(s.players[0].gold,gold-Math.max(0,CARDS[id].cost-1))});
test('Medallion is discarded; cannot be used twice',()=>{let s=fixture('Z1-01',['C01'],['T19']);s=roll(launch(s,'Z1-01'),[0]);s=act(s,{type:'loss',prevent:'medallion'});assert.equal(current(s).crew.length,1);assert.deepEqual(current(s).treasures,[]);assert(s.treasureDiscard.includes('T19'))});
test('Fortune awards newly triggered bonuses once',()=>{let s=fixture('Z2-01',['C02','C03'],['T09','T06','T16']);current(s).blessing='fortune';s=roll(launch(s,'Z2-01'),[1,1]);s=act(s,{type:'control',id:'fortune',index:0},()=>.99);assert.equal(current(s).gold,103);assert.equal(current(s).supply,98)});
test('Fortune Skull preserves Gold and triggers Black Cat',()=>{let s=fixture('Z2-01',['C02','C03'],['T09','T16']);current(s).blessing='fortune';s=roll(launch(s,'Z2-01'),[5,1]);s=act(s,{type:'control',id:'fortune',index:1},()=>0);assert.equal(current(s).gold,104);assert.equal(current(s).supply,98);assert.equal(s.exp.phase,'loss')});
test('Fortune new 2 triggers Flintlock',()=>{let s=fixture('Z1-01',['C01'],['T06']);current(s).blessing='fortune';s=roll(launch(s,'Z1-01'),[1]);s=act(s,{type:'control',id:'fortune',index:0},()=>.7);assert.equal(current(s).gold,101)});
console.log(`${passed} rules checks passed, including all 49 Mission success/failure pairs.`);
