import vm from 'node:vm';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const locs=['tavern','market','dock','work','quarters','black','veteran','witch'];
class Element{constructor(){this.dataset={};this.style={setProperty(){}};this.children=[];const cls=new Set();this.classList={add(...xs){xs.forEach(x=>cls.add(x))},remove(...xs){xs.forEach(x=>cls.delete(x))},toggle(x,v){if(v??!cls.has(x))cls.add(x);else cls.delete(x)},contains(x){return cls.has(x)}}}addEventListener(){}setAttribute(){}append(...x){this.children.push(...x)}appendChild(x){this.children.push(x)}replaceChildren(){this.children=[]}querySelector(){return new Element()}querySelectorAll(){return []}getBoundingClientRect(){return {width:1366,height:900,left:0,top:0}}}
const nodes=new Map(),hotspots=locs.map(loc=>{const n=new Element();n.dataset.location=loc;return n});
const document={getElementById(id){if(!nodes.has(id))nodes.set(id,new Element());return nodes.get(id)},querySelectorAll(s){return s.includes('.hotspot')?hotspots:[]},querySelector(){return new Element()},createElement(){return new Element()},body:new Element()};
const saved=new Map();const sandbox={document,window:{addEventListener(){},dispatchEvent(){},innerWidth:1366,innerHeight:900},localStorage:{setItem(k,v){saved.set(k,v)},getItem(k){return saved.get(k)||null}},console,setTimeout(){},clearTimeout(){},requestAnimationFrame(){},Event:class{},Math:Object.create(Math)};
let source=fs.readFileSync('game.js','utf8');source=source.replace(/\}\)\(\);\s*$/,`globalThis.api={defaultGame,missionReason,missionRoutes,routeViable,diceCount,prepareRoll,rollOptions,applyRollOption,totalRoll,attemptMission,aiTakeTurn,updateProgression,baseStat,crewInstance,CREW,TREASURES,MISSIONS, getGame:()=>game,setGame:g=>{game=g;actionBusy=false;expeditionRunning=false}};})();`);
vm.createContext(sandbox);vm.runInContext(source,sandbox);const a=sandbox.api;const setup={players:2,names:['A','B'],captains:['Anne','Black'],mode:'ai'};
let g=a.defaultGame(setup);a.setGame(g);assert.equal(a.diceCount(0),0);assert.equal(a.diceCount(3),2);assert.equal(a.diceCount(5),2);assert.equal(a.diceCount(6),3);
let p=g.players[0];p.crew=['navigator','gunner','scout','veteran_pirate'].map(a.crewInstance);p.treasures=['loaded_bones','lucky_doubloon','temple_key'];p.activeTreasures=[...p.treasures];
const m=a.MISSIONS.find(x=>x.id==='Z1-01');let e={used:{},roll:{dice:[0,1],extra:0,bonus:0,mods:[],used:{}}};let t={stat:'combat'};const o=a.rollOptions(p,m,t,e).find(x=>x.id==='loaded_bones');a.applyRollOption(o,0,p,e);assert.equal(e.roll.dice[0],2);assert(!a.rollOptions(p,m,t,e).some(x=>x.id==='loaded_bones'));e.roll={dice:[0],extra:0,bonus:0,mods:[],used:{}};assert(!a.rollOptions(p,m,t,e).some(x=>x.id==='loaded_bones'));
for(const n of [2,3,4]){g=a.defaultGame({...setup,players:n,names:Array(n).fill('Test'),captains:Array(n).fill('Captain')});a.setGame(g);assert.equal(g.fullState.active[1].length,n+2);g.fullState.progress={1:n===2?1:2,2:n===4?3:2,3:n===2?2:n===3?3:4};a.updateProgression(false);assert(g.fullState.finalUnlocked);assert(g.fullState.unlocks.black);assert(g.fullState.unlocks.veteran)}
// Every catalog mission resolves success and failure through the same engine used by humans and AI.
let cases=0;
for(const mission of a.MISSIONS){for(const win of [true,false]){g=a.defaultGame(setup);a.setGame(g);p=g.players[0];p.crew=['navigator','gunner','scout','veteran_pirate'].map(a.crewInstance);p.gold=50;p.supplies=6;g.fullState.revealed={1:true,2:true,3:true,4:true};g.fullState.finalUnlocked=true;g.fullState.finalId=mission.zone===4?mission.id:g.fullState.finalId;
// Fixture supplies exactly the required powers to cover mission resolution independent of crew-building strategy.
const oldStats=a.CREW.map(c=>[c,c.sailing,c.combat,c.search]);for(const c of a.CREW)c.sailing=c.combat=c.search=win?10:10;p.activeTreasures=[];p.crew=[a.crewInstance('deckhand')];sandbox.Math.random=()=>win?.99:0;await a.attemptMission(mission,0,true);assert.equal(g.expedition,null);assert.equal(g.fullState.testStats[win?'success':'fail'],1);if(win&&mission.zone===4)assert.equal(g.winner,0);if(win&&mission.zone!==4)assert(g.fullState.done[mission.id]);if(!win)assert(!g.fullState.done[mission.id]);assert(p.gold>=0&&p.supplies>=0&&p.supplies<=6);for(const [c,sa,co,se] of oldStats){c.sailing=sa;c.combat=co;c.search=se}cases++}}
console.log(`PASS: dice boundaries; ability limits across stages; 2/3/4-player progression; ${cases} mission outcome scenarios.`);
// AI full-match smoke simulation, fixed pseudo-random seeds; no rendering/timing.
let wins=0;for(let seed=1;seed<=5;seed++){let rng=seed;sandbox.Math.random=()=>{rng=(rng*1664525+1013904223)>>>0;return rng/4294967296};g=a.defaultGame(setup);g.players.forEach(p=>p.isAI=true);a.setGame(g);for(let i=0;i<600&&g.winner===null;i++){await a.aiTakeTurn();g.players.forEach(p=>p.isAI=true)}if(g.winner!==null)wins++;console.log(`AI seed ${seed}: ${g.winner===null?'no winner at cap':'winner '+g.winner} / round ${g.turn}`)}assert(wins>0,'AI must complete at least one full match');

// Browser QA fixtures use an explicitly prepared late-game save; never shipped in dist.
g=a.defaultGame(setup);a.setGame(g);g.mode='local';g.players.forEach(p=>p.isAI=false);p=g.players[0];p.crew=['navigator','gunner','scout','veteran_pirate'].map(a.crewInstance);p.gold=8;p.supplies=6;p.treasures=['loaded_bones','lucky_doubloon','fates_coin'];p.activeTreasures=[...p.treasures];g.fullState.progress={1:1,2:2,3:2};g.fullState.finalId='F-06';a.updateProgression(false);
const html=fs.readFileSync('index.html','utf8').replace('<head>','<head><base href="/">');fs.mkdirSync('tests/fixtures',{recursive:true});
for(const [name,value] of [['final-success',.99],['final-failure',0]])fs.writeFileSync('tests/fixtures/'+name+'.html',html.replace('<script src="menu.js"',`<script>localStorage.setItem('captainsDashBoardStep7',${JSON.stringify(JSON.stringify(g))});Math.random=()=>${value};</script><script src="menu.js"`));
